import {
  EquipmentDetail,
  EquipmentListRow,
  MonsterDetail,
  MonsterListRow,
  SpellDetail,
  SpellListRow,
} from '../app/core/game-data/game-data.service';

// Dev-only sample data used by the mock interceptor so the Spells, Monsters and
// Equipment screens are browsable without the Cloudflare Worker. Shortened,
// paraphrased entries: the real text comes from the SRD 5.2.1 tables in
// dnd-db-rest. Never bundled in production (loaded lazily when
// environment.useMockApi is true).
export const spells: (SpellListRow & SpellDetail)[] = [
  {
    spellID: 1,
    spellName: 'Fire Bolt',
    spellLevel: 0,
    schoolName: 'Evocation',
    spellCastingTime: 'Action',
    spellIsRitual: 0,
    spellRange: '120 feet',
    spellConcentration: 0,
    spellDuration: 'Instantaneous',
    spellClasses: 'Sorcerer, Wizard',
    spellVerbal: 1,
    spellSomatic: 1,
    spellMaterial: null,
    spellDescription:
      'You hurl a mote of fire at a creature or object within range. On a hit the target takes fire damage, and a flammable object it is not wearing or carrying ignites.',
    spellHigherLevel: 'The damage increases when you reach levels 5, 11 and 17.',
    active: 1,
  },
  {
    spellID: 2,
    spellName: 'Magic Missile',
    spellLevel: 1,
    schoolName: 'Evocation',
    spellCastingTime: 'Action',
    spellIsRitual: 0,
    spellRange: '120 feet',
    spellConcentration: 0,
    spellDuration: 'Instantaneous',
    spellClasses: 'Sorcerer, Wizard',
    spellVerbal: 1,
    spellSomatic: 1,
    spellMaterial: null,
    spellDescription:
      'Three darts of magical force strike creatures of your choice that you can see within range. Each dart deals force damage and always hits.',
    spellHigherLevel: 'The spell creates one more dart for each slot level above 1.',
    active: 1,
  },
  {
    spellID: 3,
    spellName: 'Cure Wounds',
    spellLevel: 1,
    schoolName: 'Abjuration',
    spellCastingTime: 'Action',
    spellIsRitual: 0,
    spellRange: 'Touch',
    spellConcentration: 0,
    spellDuration: 'Instantaneous',
    spellClasses: 'Bard, Cleric, Druid, Paladin, Ranger',
    spellVerbal: 1,
    spellSomatic: 1,
    spellMaterial: null,
    spellDescription:
      'A creature you touch regains hit points equal to a die roll plus your spellcasting modifier.',
    spellHigherLevel: 'The healing increases by one die for each slot level above 1.',
    active: 1,
  },
  {
    spellID: 4,
    spellName: 'Detect Magic',
    spellLevel: 1,
    schoolName: 'Divination',
    spellCastingTime: 'Action',
    spellIsRitual: 1,
    spellRange: 'Self',
    spellConcentration: 1,
    spellDuration: 'Up to 10 minutes',
    spellClasses: 'Bard, Cleric, Druid, Paladin, Ranger, Sorcerer, Wizard',
    spellVerbal: 1,
    spellSomatic: 1,
    spellMaterial: null,
    spellDescription:
      'For the duration you sense the presence of magic within 30 feet of you. You can use your action to see a faint aura around any visible magical creature or object.',
    spellHigherLevel: null,
    active: 1,
  },
  {
    spellID: 5,
    spellName: 'Fireball',
    spellLevel: 3,
    schoolName: 'Evocation',
    spellCastingTime: 'Action',
    spellIsRitual: 0,
    spellRange: '150 feet',
    spellConcentration: 0,
    spellDuration: 'Instantaneous',
    spellClasses: 'Sorcerer, Wizard',
    spellVerbal: 1,
    spellSomatic: 1,
    spellMaterial: 'A ball of bat guano and sulfur',
    spellDescription:
      'A bright streak flashes to a point you choose and blossoms into an explosion of flame. Each creature in a 20-foot-radius sphere makes a Dexterity saving throw, taking fire damage on a failure or half as much on a success.',
    spellHigherLevel: 'The damage increases for each slot level above 3.',
    active: 1,
  },
  {
    spellID: 6,
    spellName: 'Hold Person',
    spellLevel: 2,
    schoolName: 'Enchantment',
    spellCastingTime: 'Action',
    spellIsRitual: 0,
    spellRange: '60 feet',
    spellConcentration: 1,
    spellDuration: 'Up to 1 minute',
    spellClasses: 'Bard, Cleric, Druid, Sorcerer, Warlock, Wizard',
    spellVerbal: 1,
    spellSomatic: 1,
    spellMaterial: 'A straight piece of iron',
    spellDescription:
      'Choose a humanoid you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration, repeating the save at the end of each of its turns.',
    spellHigherLevel: 'You can target one additional humanoid for each slot level above 2.',
    active: 1,
  },
  {
    spellID: 7,
    spellName: 'Polymorph',
    spellLevel: 4,
    schoolName: 'Transmutation',
    spellCastingTime: 'Action',
    spellIsRitual: 0,
    spellRange: '60 feet',
    spellConcentration: 1,
    spellDuration: 'Up to 1 hour',
    spellClasses: 'Bard, Druid, Sorcerer, Wizard',
    spellVerbal: 1,
    spellSomatic: 1,
    spellMaterial: 'A caterpillar cocoon',
    spellDescription:
      'You transform a creature you can see within range into a new form. An unwilling creature can resist with a Wisdom saving throw. The new form can be any beast whose challenge rating is no higher than the target’s.',
    spellHigherLevel: null,
    active: 1,
  },
  {
    spellID: 8,
    spellName: 'Wish',
    spellLevel: 9,
    schoolName: 'Conjuration',
    spellCastingTime: 'Action',
    spellIsRitual: 0,
    spellRange: 'Self',
    spellConcentration: 0,
    spellDuration: 'Instantaneous',
    spellClasses: 'Sorcerer, Wizard',
    spellVerbal: 1,
    spellSomatic: 0,
    spellMaterial: null,
    spellDescription:
      'The mightiest spell a mortal can cast. You can duplicate any other spell of 8th level or lower, or attempt something greater at the risk of never casting Wish again.',
    spellHigherLevel: null,
    active: 1,
  },
];

export const monsters: (MonsterListRow & MonsterDetail)[] = [
  {
    monsterID: 1,
    monsterName: 'Goblin Warrior',
    creatureTypeName: 'Fey',
    crLabel: '1/4',
    crValue: 0.25,
    xp: 50,
    monsterAc: 15,
    monsterHpAvg: 10,
    monsterSizes: 'Small',
    monsterGroup: 'Goblins',
    monsterTypeTags: '(Goblinoid)',
    monsterAlignment: 'Chaotic Neutral',
    monsterAcNote: 'leather armor, shield',
    monsterHpDiceCount: 3,
    monsterHpDiceSides: 6,
    monsterHpBonus: 0,
    monsterStr: 8,
    monsterDex: 15,
    monsterCon: 10,
    monsterInt: 10,
    monsterWis: 8,
    monsterCha: 8,
    monsterPassivePerception: 9,
    monsterLanguages: 'Common, Goblin',
    monsterDescription:
      'Small, quick and spiteful, goblins prefer ambushes and retreats to a fair fight.',
    active: 1,
  },
  {
    monsterID: 2,
    monsterName: 'Wolf',
    creatureTypeName: 'Beast',
    crLabel: '1/4',
    crValue: 0.25,
    xp: 50,
    monsterAc: 12,
    monsterHpAvg: 11,
    monsterSizes: 'Medium',
    monsterGroup: 'Animals',
    monsterTypeTags: null,
    monsterAlignment: 'Unaligned',
    monsterAcNote: 'natural armor',
    monsterHpDiceCount: 2,
    monsterHpDiceSides: 8,
    monsterHpBonus: 2,
    monsterStr: 14,
    monsterDex: 15,
    monsterCon: 12,
    monsterInt: 3,
    monsterWis: 12,
    monsterCha: 6,
    monsterPassivePerception: 13,
    monsterLanguages: null,
    monsterDescription: 'Pack hunters that gain an edge when an ally is next to their target.',
    active: 1,
  },
  {
    monsterID: 3,
    monsterName: 'Skeleton',
    creatureTypeName: 'Undead',
    crLabel: '1/4',
    crValue: 0.25,
    xp: 50,
    monsterAc: 14,
    monsterHpAvg: 13,
    monsterSizes: 'Medium',
    monsterGroup: null,
    monsterTypeTags: null,
    monsterAlignment: 'Lawful Evil',
    monsterAcNote: 'armor scraps',
    monsterHpDiceCount: 2,
    monsterHpDiceSides: 8,
    monsterHpBonus: 4,
    monsterStr: 10,
    monsterDex: 16,
    monsterCon: 15,
    monsterInt: 6,
    monsterWis: 8,
    monsterCha: 5,
    monsterPassivePerception: 9,
    monsterLanguages: 'Understands the languages it knew in life but can’t speak',
    monsterDescription: null,
    active: 1,
  },
  {
    monsterID: 4,
    monsterName: 'Ogre',
    creatureTypeName: 'Giant',
    crLabel: '2',
    crValue: 2,
    xp: 450,
    monsterAc: 11,
    monsterHpAvg: 68,
    monsterSizes: 'Large',
    monsterGroup: null,
    monsterTypeTags: null,
    monsterAlignment: 'Chaotic Evil',
    monsterAcNote: 'hide armor',
    monsterHpDiceCount: 8,
    monsterHpDiceSides: 10,
    monsterHpBonus: 24,
    monsterStr: 19,
    monsterDex: 8,
    monsterCon: 16,
    monsterInt: 5,
    monsterWis: 7,
    monsterCha: 7,
    monsterPassivePerception: 8,
    monsterLanguages: 'Common, Giant',
    monsterDescription: 'Brutish and hungry, ogres swing greatclubs with more strength than sense.',
    active: 1,
  },
  {
    monsterID: 5,
    monsterName: 'Owlbear',
    creatureTypeName: 'Monstrosity',
    crLabel: '3',
    crValue: 3,
    xp: 700,
    monsterAc: 13,
    monsterHpAvg: 59,
    monsterSizes: 'Large',
    monsterGroup: null,
    monsterTypeTags: null,
    monsterAlignment: 'Unaligned',
    monsterAcNote: 'natural armor',
    monsterHpDiceCount: 7,
    monsterHpDiceSides: 10,
    monsterHpBonus: 21,
    monsterStr: 20,
    monsterDex: 12,
    monsterCon: 17,
    monsterInt: 3,
    monsterWis: 12,
    monsterCha: 7,
    monsterPassivePerception: 13,
    monsterLanguages: null,
    monsterDescription: 'A ferocious cross between a giant owl and a bear.',
    active: 1,
  },
  {
    monsterID: 6,
    monsterName: 'Gelatinous Cube',
    creatureTypeName: 'Ooze',
    crLabel: '2',
    crValue: 2,
    xp: 450,
    monsterAc: 6,
    monsterHpAvg: 63,
    monsterSizes: 'Large',
    monsterGroup: null,
    monsterTypeTags: null,
    monsterAlignment: 'Unaligned',
    monsterAcNote: null,
    monsterHpDiceCount: 6,
    monsterHpDiceSides: 10,
    monsterHpBonus: 30,
    monsterStr: 14,
    monsterDex: 3,
    monsterCon: 20,
    monsterInt: 1,
    monsterWis: 6,
    monsterCha: 1,
    monsterPassivePerception: 8,
    monsterLanguages: null,
    monsterDescription: 'A nearly transparent cube that scours dungeon corridors clean.',
    active: 1,
  },
  {
    monsterID: 7,
    monsterName: 'Giant (Hill or Stone)',
    creatureTypeName: 'Giant',
    crLabel: '5',
    crValue: 5,
    xp: 1800,
    monsterAc: 13,
    monsterHpAvg: 105,
    monsterSizes: 'Huge or Large',
    monsterGroup: null,
    monsterTypeTags: null,
    monsterAlignment: 'Neutral',
    monsterAcNote: null,
    monsterHpDiceCount: 10,
    monsterHpDiceSides: 12,
    monsterHpBonus: 40,
    monsterStr: 21,
    monsterDex: 8,
    monsterCon: 19,
    monsterInt: 5,
    monsterWis: 9,
    monsterCha: 6,
    monsterPassivePerception: 12,
    monsterLanguages: 'Giant',
    monsterDescription: 'This entry covers a creature that appears in more than one size.',
    active: 1,
  },
  {
    monsterID: 8,
    monsterName: 'Adult Red Dragon',
    creatureTypeName: 'Dragon',
    crLabel: '17',
    crValue: 17,
    xp: 18000,
    monsterAc: 19,
    monsterHpAvg: 256,
    monsterSizes: 'Huge',
    monsterGroup: 'Dragons',
    monsterTypeTags: null,
    monsterAlignment: 'Chaotic Evil',
    monsterAcNote: 'natural armor',
    monsterHpDiceCount: 19,
    monsterHpDiceSides: 12,
    monsterHpBonus: 133,
    monsterStr: 27,
    monsterDex: 10,
    monsterCon: 25,
    monsterInt: 16,
    monsterWis: 13,
    monsterCha: 21,
    monsterPassivePerception: 23,
    monsterLanguages: 'Common, Draconic',
    monsterDescription:
      'Greedy and proud, red dragons nest in volcanic peaks and hoard vast treasure.',
    active: 1,
  },
];

export const equipment: (EquipmentListRow & EquipmentDetail)[] = [
  {
    equipmentID: 1,
    equipmentName: 'Longsword',
    equipmentKind: 'weapon',
    costCp: 1500,
    weightLb: 3,
    weaponCategory: 'Martial',
    weaponRange: 'Melee',
    damageDiceCount: 1,
    damageDiceSides: 8,
    damageTypeName: 'Slashing',
    masteryName: 'Sap',
    armorCategory: null,
    armorBaseAc: null,
    armorDexCap: null,
    equipmentDescription: 'Versatile: deals a larger die when wielded with two hands.',
    active: 1,
  },
  {
    equipmentID: 2,
    equipmentName: 'Dagger',
    equipmentKind: 'weapon',
    costCp: 200,
    weightLb: 1,
    weaponCategory: 'Simple',
    weaponRange: 'Melee',
    damageDiceCount: 1,
    damageDiceSides: 4,
    damageTypeName: 'Piercing',
    masteryName: 'Nick',
    armorCategory: null,
    armorBaseAc: null,
    armorDexCap: null,
    equipmentDescription: 'Finesse, light and thrown (range 20/60).',
    active: 1,
  },
  {
    equipmentID: 3,
    equipmentName: 'Chain Mail',
    equipmentKind: 'armor',
    costCp: 7500,
    weightLb: 55,
    weaponCategory: null,
    weaponRange: null,
    damageDiceCount: null,
    damageDiceSides: null,
    damageTypeName: null,
    masteryName: null,
    armorCategory: 'Heavy',
    armorBaseAc: 16,
    armorDexCap: 0,
    equipmentDescription: 'Requires Strength 13; imposes disadvantage on Stealth checks.',
    active: 1,
  },
  {
    equipmentID: 4,
    equipmentName: 'Leather Armor',
    equipmentKind: 'armor',
    costCp: 1000,
    weightLb: 10,
    weaponCategory: null,
    weaponRange: null,
    damageDiceCount: null,
    damageDiceSides: null,
    damageTypeName: null,
    masteryName: null,
    armorCategory: 'Light',
    armorBaseAc: 11,
    armorDexCap: null,
    equipmentDescription: null,
    active: 1,
  },
  {
    equipmentID: 5,
    equipmentName: 'Thieves’ Tools',
    equipmentKind: 'tool',
    costCp: 2500,
    weightLb: 1,
    weaponCategory: null,
    weaponRange: null,
    damageDiceCount: null,
    damageDiceSides: null,
    damageTypeName: null,
    masteryName: null,
    armorCategory: null,
    armorBaseAc: null,
    armorDexCap: null,
    equipmentDescription: 'Lets you pick locks and disarm traps.',
    active: 1,
  },
  {
    equipmentID: 6,
    equipmentName: 'Rope, Hempen (50 feet)',
    equipmentKind: 'gear',
    costCp: 100,
    weightLb: 10,
    weaponCategory: null,
    weaponRange: null,
    damageDiceCount: null,
    damageDiceSides: null,
    damageTypeName: null,
    masteryName: null,
    armorCategory: null,
    armorBaseAc: null,
    armorDexCap: null,
    equipmentDescription: 'Can be burst with a Strength check.',
    active: 1,
  },
  {
    equipmentID: 7,
    equipmentName: 'Arrows (20)',
    equipmentKind: 'ammunition',
    costCp: 100,
    weightLb: 1,
    weaponCategory: null,
    weaponRange: null,
    damageDiceCount: null,
    damageDiceSides: null,
    damageTypeName: null,
    masteryName: null,
    armorCategory: null,
    armorBaseAc: null,
    armorDexCap: null,
    equipmentDescription: null,
    active: 1,
  },
  {
    equipmentID: 8,
    equipmentName: 'Riding Horse',
    equipmentKind: 'mount',
    costCp: 7500,
    weightLb: null,
    weaponCategory: null,
    weaponRange: null,
    damageDiceCount: null,
    damageDiceSides: null,
    damageTypeName: null,
    masteryName: null,
    armorCategory: null,
    armorBaseAc: null,
    armorDexCap: null,
    equipmentDescription: null,
    active: 1,
  },
  {
    equipmentID: 9,
    equipmentName: 'Torch',
    equipmentKind: 'gear',
    costCp: 1,
    weightLb: 1,
    weaponCategory: null,
    weaponRange: null,
    damageDiceCount: null,
    damageDiceSides: null,
    damageTypeName: null,
    masteryName: null,
    armorCategory: null,
    armorBaseAc: null,
    armorDexCap: null,
    equipmentDescription: 'Burns for 1 hour, shedding bright light in a 20-foot radius.',
    active: 1,
  },
  {
    equipmentID: 10,
    equipmentName: 'Explorer’s Pack',
    equipmentKind: 'pack',
    costCp: 1000,
    weightLb: 55,
    weaponCategory: null,
    weaponRange: null,
    damageDiceCount: null,
    damageDiceSides: null,
    damageTypeName: null,
    masteryName: null,
    armorCategory: null,
    armorBaseAc: null,
    armorDexCap: null,
    equipmentDescription:
      'A backpack, bedroll, rations, torches, a tinderbox, a waterskin and rope.',
    active: 1,
  },
];
