import { Item } from '../app/core/items/items.service';

// Dev-only sample catalog used by the mock interceptor so the UI is fully
// browsable without the Cloudflare Worker backend. Never bundled in production
// (loaded lazily only when environment.useMockApi is true).
export const items: Item[] = [
  {
    itemID: 1,
    itemName: 'Bag of Holding',
    itemRarity: 'Uncommon',
    itemCost: 500,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'No',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/bag-of-holding',
    itemVisualDesc: 'A plain grey sack, deceptively deep.',
    itemShopkeeperDesc: 'Never lose your rations again — nor your spare halberd.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 2,
    itemName: 'Cloak of Protection',
    itemRarity: 'Uncommon',
    itemCost: 3500,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/cloak-of-protection',
    itemVisualDesc: 'Deep blue wool trimmed with silver thread.',
    itemShopkeeperDesc: 'A little luck woven into every stitch.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 3,
    itemName: 'Amulet of Health',
    itemRarity: 'Rare',
    itemCost: 8000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/amulet-of-health',
    itemVisualDesc: 'A ruby pendant that pulses like a heartbeat.',
    itemShopkeeperDesc: 'For the adventurer who refuses to stay down.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 4,
    itemName: 'Flame Tongue',
    itemRarity: 'Rare',
    itemCost: 5000,
    itemType: 'Weapon (any sword)',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/flame-tongue',
    itemVisualDesc: 'The blade erupts in roaring fire on command.',
    itemShopkeeperDesc: 'Warms the hands and the hearts of your enemies.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 5,
    itemName: 'Boots of Speed',
    itemRarity: 'Rare',
    itemCost: 4000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/boots-of-speed',
    itemVisualDesc: 'Supple leather that seems to hum with motion.',
    itemShopkeeperDesc: 'Click your heels and leave your troubles behind.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 6,
    itemName: 'Ring of Spell Storing',
    itemRarity: 'Rare',
    itemCost: 24000,
    itemType: 'Ring',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/ring-of-spell-storing',
    itemVisualDesc: 'A band of pale gold set with a hollow crystal.',
    itemShopkeeperDesc: 'A spell in your pocket for a rainy dungeon.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 7,
    itemName: 'Staff of Power',
    itemRarity: 'Very Rare',
    itemCost: 95000,
    itemType: 'Staff',
    itemRestrictions: 'Sorcerer, Warlock, Wizard',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/staff-of-power',
    itemVisualDesc: 'Gnarled darkwood crowned with a crackling gem.',
    itemShopkeeperDesc: 'Only for those who can bear its weight — in every sense.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 8,
    itemName: 'Cloak of Displacement',
    itemRarity: 'Rare',
    itemCost: 60000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/cloak-of-displacement',
    itemVisualDesc: 'The wearer seems to stand a half-step from where they are.',
    itemShopkeeperDesc: 'Now you see them, now you very much do not.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 9,
    itemName: 'Vorpal Sword',
    itemRarity: 'Legendary',
    itemCost: 120000,
    itemType: 'Weapon (any sword that deals slashing damage)',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/vorpal-sword',
    itemVisualDesc: 'An edge so keen it whispers as it moves.',
    itemShopkeeperDesc: 'Mind the pointy end — and your foe’s neck.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 10,
    itemName: 'Holy Avenger',
    itemRarity: 'Legendary',
    itemCost: 165000,
    itemType: 'Weapon (any sword)',
    itemRestrictions: 'Paladin',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/holy-avenger',
    itemVisualDesc: 'The blade glows with a soft, righteous light.',
    itemShopkeeperDesc: 'For the truly virtuous. References required.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 11,
    itemName: 'Deck of Many Things',
    itemRarity: 'Artifact',
    itemCost: 200000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'No',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/deck-of-many-things',
    itemVisualDesc: 'A worn deck of cards that hums with fate.',
    itemShopkeeperDesc: 'All sales final. No refunds. No survivors, occasionally.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 12,
    itemName: 'Potion of Healing',
    itemRarity: 'Common',
    itemCost: 50,
    itemType: 'Potion',
    itemRestrictions: 'None',
    itemAttunement: 'No',
    itemSource: 'Player’s Handbook',
    itemUrl: 'https://www.dndbeyond.com/magic-items/potion-of-healing',
    itemVisualDesc: 'Red liquid that shimmers when shaken.',
    itemShopkeeperDesc: 'Buy a dozen. Trust me, you’ll want a dozen.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 13,
    itemName: 'Immovable Rod',
    itemRarity: 'Uncommon',
    itemCost: 5000,
    itemType: 'Rod',
    itemRestrictions: 'None',
    itemAttunement: 'No',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/immovable-rod',
    itemVisualDesc: 'A flat iron rod with a small button.',
    itemShopkeeperDesc: 'The most versatile tool you’ll ever wedge into a door.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 14,
    itemName: 'Robe of the Archmagi',
    itemRarity: 'Legendary',
    itemCost: 130000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'Sorcerer, Warlock, Wizard',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/robe-of-the-archmagi',
    itemVisualDesc: 'Embroidered with sigils that drift across the cloth.',
    itemShopkeeperDesc: 'Dress for the archmage you wish to become.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 15,
    itemName: 'Alchemy Jug (sample)',
    itemRarity: 'Uncommon',
    itemCost: 6000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'No',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/alchemy-jug',
    itemVisualDesc: '',
    itemShopkeeperDesc: '',
    active: 1,
    itemDescription:
      'This stoppered ceramic jug produces a liquid of your choice each dawn: up to 2 gallons of acid, basic poison, beer, honey, mayonnaise, oil, vinegar, or fresh water. Sample text written for the dev catalog, not taken from any rulebook.',
    itemDescriptionSource: 'SRD 5.2.1, CC-BY-4.0',
  },
  {
    itemID: 16,
    itemName: 'Ashen Reliquary (sample)',
    itemRarity: 'Rare',
    itemCost: 12000,
    itemType: 'Wondrous Item',
    itemRestrictions: null,
    itemAttunement: 'Yes',
    itemSource: 'Xanathar’s Guide to Everything',
    itemUrl: 'https://www.dndbeyond.com/magic-items/ashen-reliquary',
    itemVisualDesc: '',
    itemShopkeeperDesc: '',
    active: 1,
    itemDescription:
      'While you hold this reliquary, you gain the following benefits.\nSoothing Embers. You regain 1d6 hit points at the start of each of your turns while you have at least 1 hit point.\nAshen Veil. You can cast invisibility (self only) once per dawn.\n\nThe reliquary has the following table of charges:\n\nCharges | Effect\n1 | Ember Ward\n2 | Ash Storm\n3 | Phoenix Rising',
    itemDescriptionSource: 'D&D Beyond',
  },
  {
    itemID: 17,
    itemName: 'Ashlar Censer (sample)',
    itemRarity: 'Common',
    itemCost: 50,
    itemType: 'Wondrous Item',
    itemRestrictions: null,
    itemAttunement: 'No',
    itemSource: 'Sample Catalog',
    itemUrl: 'https://www.dndbeyond.com/magic-items/ashlar-censer',
    itemVisualDesc: '',
    itemShopkeeperDesc: '',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 18,
    itemName: 'Arcane Lantern (sample)',
    itemRarity: 'Uncommon',
    itemCost: 300,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'No',
    itemSource: 'Sample Catalog',
    itemUrl: 'https://www.dndbeyond.com/magic-items/arcane-lantern',
    itemVisualDesc: 'A brass lantern whose flame is the colour of deep water.',
    itemShopkeeperDesc: 'Never stumble in a crypt again.',
    active: 1,
    itemDescription: null,
    itemDescriptionSource: null,
  },
  {
    itemID: 19,
    itemName: 'Anchor of Endless Tides (sample)',
    itemRarity: 'Very Rare',
    itemCost: 40000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'Sorcerer, Warlock, Wizard',
    itemAttunement: 'Yes',
    itemSource: 'Sample Catalog',
    itemUrl: 'https://www.dndbeyond.com/magic-items/anchor-of-endless-tides',
    itemVisualDesc: 'Barnacled iron, cold to the touch.',
    itemShopkeeperDesc: 'Drop it anywhere; the sea will follow.',
    active: 1,
    itemDescription:
      'Sample sentence 1 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Sample sentence 2 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Sample sentence 3 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Sample sentence 4 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Sample sentence 5 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Sample sentence 6 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Sample sentence 7 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Sample sentence 8 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Sample sentence 9 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Sample sentence 10 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Sample sentence 11 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Sample sentence 12 of a deliberately long rules description that keeps going so the wrapping, line length and overall panel height can be judged at every viewport width, in light and in dark mode. Unbroken token: Supercalifragilisticexpialidocious_Supercalifragilisticexpialidocious_Supercalifragilisticexpialidocious_Supercalifragilisticexpialidocious_Supercalifragilisticexpialidocious_Supercalifragilisticexpialidocious_end.',
    itemDescriptionSource: 'SRD 5.2.1, CC-BY-4.0',
  },
  {
    itemID: 20,
    itemName: 'Amulet of the Lost Star (sample)',
    itemRarity: 'Artifact',
    itemCost: 0,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Sample Catalog',
    itemUrl: 'https://www.dndbeyond.com/magic-items/amulet-of-the-lost-star',
    itemVisualDesc: '',
    itemShopkeeperDesc: '',
    active: 1,
    itemDescription: 'A short sample artifact description sourced from D&D Beyond.',
    itemDescriptionSource: 'D&D Beyond',
  },
  {
    itemID: 21,
    itemName: 'Retired Relic (sample, inactive)',
    itemRarity: 'Rare',
    itemCost: 100,
    itemType: 'Wondrous Item',
    itemRestrictions: null,
    itemAttunement: 'No',
    itemSource: 'Sample Catalog',
    itemUrl: 'https://www.dndbeyond.com/magic-items/retired-relic',
    itemVisualDesc: '',
    itemShopkeeperDesc: '',
    active: 0,
    itemDescription: 'This row is inactive and must never be shown.',
    itemDescriptionSource: 'D&D Beyond',
  },
  {
    itemID: 22,
    itemName: 'Ambered Scroll Case (sample)',
    itemRarity: 'Common',
    itemCost: 25,
    itemType: 'Wondrous Item',
    itemRestrictions: null,
    itemAttunement: 'No',
    itemSource: 'Sample Catalog',
    itemUrl: 'https://www.dndbeyond.com/magic-items/ambered-scroll-case',
    itemVisualDesc: '',
    itemShopkeeperDesc: '',
    active: 1,
    itemDescription:
      'Holds up to ten scrolls and keeps them dry. Sample third-party-style text with a provenance label we do not recognise.',
    itemDescriptionSource: 'Homebrew Notes',
  },
];
