import { Item } from '../app/core/items/items.service';

// Dev-only sample catalog used by the mock interceptor so the UI is fully
// browsable without the Cloudflare Worker backend. Never bundled in production
// (loaded lazily only when environment.useMockApi is true).
export const items: Item[] = [
  {
    itemID: 1,
    itemName: 'Bag of Holding',
    itemRarity: 'Uncommon',
    itemCost: 500,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'No',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/bag-of-holding',
    itemVisualDesc: 'A plain grey sack, deceptively deep.',
    itemShopkeeperDesc: 'Never lose your rations again — nor your spare halberd.',
  },
  {
    itemID: 2,
    itemName: 'Cloak of Protection',
    itemRarity: 'Uncommon',
    itemCost: 3500,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/cloak-of-protection',
    itemVisualDesc: 'Deep blue wool trimmed with silver thread.',
    itemShopkeeperDesc: 'A little luck woven into every stitch.',
  },
  {
    itemID: 3,
    itemName: 'Amulet of Health',
    itemRarity: 'Rare',
    itemCost: 8000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/amulet-of-health',
    itemVisualDesc: 'A ruby pendant that pulses like a heartbeat.',
    itemShopkeeperDesc: 'For the adventurer who refuses to stay down.',
  },
  {
    itemID: 4,
    itemName: 'Flame Tongue',
    itemRarity: 'Rare',
    itemCost: 5000,
    itemType: 'Weapon (any sword)',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/flame-tongue',
    itemVisualDesc: 'The blade erupts in roaring fire on command.',
    itemShopkeeperDesc: 'Warms the hands and the hearts of your enemies.',
  },
  {
    itemID: 5,
    itemName: 'Boots of Speed',
    itemRarity: 'Rare',
    itemCost: 4000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/boots-of-speed',
    itemVisualDesc: 'Supple leather that seems to hum with motion.',
    itemShopkeeperDesc: 'Click your heels and leave your troubles behind.',
  },
  {
    itemID: 6,
    itemName: 'Ring of Spell Storing',
    itemRarity: 'Rare',
    itemCost: 24000,
    itemType: 'Ring',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/ring-of-spell-storing',
    itemVisualDesc: 'A band of pale gold set with a hollow crystal.',
    itemShopkeeperDesc: 'A spell in your pocket for a rainy dungeon.',
  },
  {
    itemID: 7,
    itemName: 'Staff of Power',
    itemRarity: 'Very Rare',
    itemCost: 95000,
    itemType: 'Staff',
    itemRestrictions: 'Sorcerer, Warlock, Wizard',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/staff-of-power',
    itemVisualDesc: 'Gnarled darkwood crowned with a crackling gem.',
    itemShopkeeperDesc: 'Only for those who can bear its weight — in every sense.',
  },
  {
    itemID: 8,
    itemName: 'Cloak of Displacement',
    itemRarity: 'Rare',
    itemCost: 60000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/cloak-of-displacement',
    itemVisualDesc: 'The wearer seems to stand a half-step from where they are.',
    itemShopkeeperDesc: 'Now you see them, now you very much do not.',
  },
  {
    itemID: 9,
    itemName: 'Vorpal Sword',
    itemRarity: 'Legendary',
    itemCost: 120000,
    itemType: 'Weapon (any sword that deals slashing damage)',
    itemRestrictions: 'None',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/vorpal-sword',
    itemVisualDesc: 'An edge so keen it whispers as it moves.',
    itemShopkeeperDesc: 'Mind the pointy end — and your foe’s neck.',
  },
  {
    itemID: 10,
    itemName: 'Holy Avenger',
    itemRarity: 'Legendary',
    itemCost: 165000,
    itemType: 'Weapon (any sword)',
    itemRestrictions: 'Paladin',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/holy-avenger',
    itemVisualDesc: 'The blade glows with a soft, righteous light.',
    itemShopkeeperDesc: 'For the truly virtuous. References required.',
  },
  {
    itemID: 11,
    itemName: 'Deck of Many Things',
    itemRarity: 'Artifact',
    itemCost: 200000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'None',
    itemAttunement: 'No',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/deck-of-many-things',
    itemVisualDesc: 'A worn deck of cards that hums with fate.',
    itemShopkeeperDesc: 'All sales final. No refunds. No survivors, occasionally.',
  },
  {
    itemID: 12,
    itemName: 'Potion of Healing',
    itemRarity: 'Common',
    itemCost: 50,
    itemType: 'Potion',
    itemRestrictions: 'None',
    itemAttunement: 'No',
    itemSource: 'Player’s Handbook',
    itemUrl: 'https://www.dndbeyond.com/magic-items/potion-of-healing',
    itemVisualDesc: 'Red liquid that shimmers when shaken.',
    itemShopkeeperDesc: 'Buy a dozen. Trust me, you’ll want a dozen.',
  },
  {
    itemID: 13,
    itemName: 'Immovable Rod',
    itemRarity: 'Uncommon',
    itemCost: 5000,
    itemType: 'Rod',
    itemRestrictions: 'None',
    itemAttunement: 'No',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/immovable-rod',
    itemVisualDesc: 'A flat iron rod with a small button.',
    itemShopkeeperDesc: 'The most versatile tool you’ll ever wedge into a door.',
  },
  {
    itemID: 14,
    itemName: 'Robe of the Archmagi',
    itemRarity: 'Legendary',
    itemCost: 130000,
    itemType: 'Wondrous Item',
    itemRestrictions: 'Sorcerer, Warlock, Wizard',
    itemAttunement: 'Yes',
    itemSource: 'Dungeon Master’s Guide',
    itemUrl: 'https://www.dndbeyond.com/magic-items/robe-of-the-archmagi',
    itemVisualDesc: 'Embroidered with sigils that drift across the cloth.',
    itemShopkeeperDesc: 'Dress for the archmage you wish to become.',
  },
];
